mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
    useGeneratedKeys: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kci.moodstore.auth.model
secure:
  ignore:
    urls:
      - null
      - /oauth/token
server:
  port: 9012
spring:
  application:
    name: moodstore-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - filters:
            - StripPrefix=1
          id: moodstore-api-route
          predicates:
            - Path=/api/**
          uri: lb://moodstore-api
        - filters:
            - StripPrefix=1
          id: moodstore-auth-route
          predicates:
            - Path=/auth/**
          uri: lb://moodstore-auth
    nacos:
      discovery:
        server-addr: 43.139.188.90:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://43.139.188.90:3306/moodstore?serverTimezone=GMT%2b8
    username: root
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  profiles:
    active: dev
  redis:
    database: 10
    host: 43.139.188.90
    jedis:
      pool:
        max-idle: 8
        max-wait: -1ms
    password: ''
    port: 6379
    timeout: 5000
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9091/rsa/publicKey
